// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_vMUvh7n-4AgTXDUK_LJHfWNA3DT1n24',
    appId: '1:818885318898:web:edb373a9eccc740b94986b',
    messagingSenderId: '818885318898',
    projectId: 'ldsw-3-7-7e8d1',
    authDomain: 'ldsw-3-7-7e8d1.firebaseapp.com',
    storageBucket: 'ldsw-3-7-7e8d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvuSpxDmHoIyYAuzs82jq87RuzN8kfqE',
    appId: '1:818885318898:android:216ea874e4952bff94986b',
    messagingSenderId: '818885318898',
    projectId: 'ldsw-3-7-7e8d1',
    storageBucket: 'ldsw-3-7-7e8d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4GSnskeS0DE44SJ8jGenyRHmWk_PSdo',
    appId: '1:818885318898:ios:1f61a6f26f83551694986b',
    messagingSenderId: '818885318898',
    projectId: 'ldsw-3-7-7e8d1',
    storageBucket: 'ldsw-3-7-7e8d1.appspot.com',
    iosBundleId: 'com.example.ldsw37',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf4GSnskeS0DE44SJ8jGenyRHmWk_PSdo',
    appId: '1:818885318898:ios:1f61a6f26f83551694986b',
    messagingSenderId: '818885318898',
    projectId: 'ldsw-3-7-7e8d1',
    storageBucket: 'ldsw-3-7-7e8d1.appspot.com',
    iosBundleId: 'com.example.ldsw37',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_vMUvh7n-4AgTXDUK_LJHfWNA3DT1n24',
    appId: '1:818885318898:web:386a06ec7563057194986b',
    messagingSenderId: '818885318898',
    projectId: 'ldsw-3-7-7e8d1',
    authDomain: 'ldsw-3-7-7e8d1.firebaseapp.com',
    storageBucket: 'ldsw-3-7-7e8d1.appspot.com',
  );
}
